# Generated by Django 2.0.7 on 2018-08-08 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manualtest', '0003_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=64)),
                ('observation', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='featurename',
            name='product',
        ),
        migrations.AddField(
            model_name='testcase',
            name='teststep',
            field=models.CharField(default=111, max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FeatureName',
        ),
        migrations.AddField(
            model_name='testrun',
            name='testcasemapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manualtest.TestCase'),
        ),
    ]
