# Generated by Django 2.0.7 on 2018-08-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manualtest', '0005_auto_20180808_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='date',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
