# Generated by Django 2.0.7 on 2018-08-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manualtest', '0006_testrun_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='user',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
